fix: Wrap addTimeLog params in 'args' object for ERPNext API
ERPNext's make_time_log method expects parameters wrapped in an 'args' object.
Previously passing params directly caused:
"TypeError: make_time_log() missing 1 required positional argument: 'args'"

Fixed by restructuring the callMethod params:
  params: { 'args': { ...actual_params } }